version: 2

models:
  - name: dim_contributors
    description: Dimension table of all unique contributors
    columns:
      - name: user_id
        description: Unique GitHub user ID (primary key)
        tests:
          - unique
          - not_null
      
      - name: login
        description: GitHub username
        tests:
          - not_null
      
      - name: user_type
        description: Type of GitHub user
        tests:
          - accepted_values:
              values: ['user', 'non-user']
              config:
                severity: error

  - name: fact_pull_requests
    description: Fact table of pull request events
    columns:
      - name: pr_id
        description: Unique pull request ID (primary key)
        tests:
          - unique
          - not_null
      
      - name: pr_number
        description: Pull request number
        tests:
          - unique
          - not_null
      
      - name: contributor_id
        description: Foreign key to dim_contributors
        tests:
          - not_null
          - relationships:
              to: ref('dim_contributors')
              field: user_id
      
      - name: created_at
        description: When PR was created
        tests:
          - not_null

  - name: fact_commits
    description: Fact table of commit events
    columns:
      - name: commit_sha
        description: Unique commit SHA (primary key)
        tests:
          - unique
          - not_null
      
      - name: commit_author_date
        description: When commit was authored
        tests:
          - not_null
      