name: 'rituals_github_analytics'
version: '1.0.0'
config-version: 2

profile: 'rituals_github'

model-paths: ["models"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  rituals_github_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts